version: "3.9"

services:

  db:
    image: postgres:latest
    container_name: videoflix_database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: videoflix_redis
    volumes:
      - redis_data:/data

  web:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file: .env
    container_name: videoflix_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - USE_GCS=False 
    volumes:
      - .:/app
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000

  rqworker:
    build:
      context: .
      dockerfile: backend.Dockerfile
    command: python manage.py rqworker default
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data:
  videoflix_media:
  videoflix_static:
